import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'ru' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  ru: {
    // Navigation
    dashboard: 'Дашборд',
    channels: 'Каналы',
    analytics: 'Аналитика',
    scheduler: 'Планировщик',
    assistant: 'Ассистент',
    partners: 'Партнеры',
    marketplace: 'Маркетплейс',
    notifications: 'Уведомления',
    profile: 'Профиль',
    settings: 'Настройки',
    
    // Common
    loading: 'Загрузка...',
    error: 'Ошибка',
    success: 'Успешно',
    cancel: 'Отмена',
    save: 'Сохранить',
    delete: 'Удалить',
    edit: 'Редактировать',
    close: 'Закрыть',
    refresh: 'Обновить',
    search: 'Поиск',
    filter: 'Фильтр',
    sort: 'Сортировка',
    export: 'Экспорт',
    import: 'Импорт',
    
    // Auth
    login: 'Войти',
    logout: 'Выйти',
    register: 'Регистрация',
    email: 'Email',
    password: 'Пароль',
    'confirm-password': 'Подтвердите пароль',
    'forgot-password': 'Забыли пароль?',
    'remember-me': 'Запомнить меня',
    
    // Dashboard
    'total-channels': 'Всего каналов',
    'total-posts': 'Всего постов',
    'total-views': 'Всего просмотров',
    'total-subscribers': 'Всего подписчиков',
    'total-reach': 'Общий охват',
    'average-engagement': 'Средняя вовлеченность',
    'overview': 'Обзор всех каналов',
    'overview-for-channel': 'Обзор канала',
    'recent-posts': 'Недавние посты',
    'no-recent-posts': 'Нет недавних постов',
    'no-scheduled-posts-for-channel': 'Нет запланированных постов для этого канала',
    'no-channel-selected': 'Канал не выбран',
    'select-channel-to-view-dashboard': 'Выберите канал для просмотра аналитики',
    'view-all-posts': 'Все посты',
    'view-all-requests': 'Все заявки',
    'posts-this-month': 'Постов в этом месяце',
    'engagement-rate': 'Вовлеченность',
    'revenue': 'Доход',
    'switching-channel': 'Переключение канала...',
    'partner-revenue': 'Доходы по партнерам',
    'total-partner-revenue': 'Общий доход от партнеров',
    'monthly-partner-income': 'Ежемесячный доход',
    'rub': '₽',
    'revenue-summary': 'Сводка доходов',
    'partner-revenue-overview': 'Обзор доходов от партнерских программ',
    'total-revenue': 'Общий доход',
    'revenue-by-partner': 'Доходы по партнерам',
    'no-partners': 'Нет партнеров',
    'view-all-partners': 'Все партнеры',
    'latest-posts-across-channels': 'Последние посты по всем каналам',
    'no-data': 'Нет данных',
    
    // Channel Management
    'add-channel': 'Добавить канал',
    'channel-name': 'Название канала',
    'channel-username': 'Имя пользователя канала',
    'channel-description': 'Описание канала',
    'channel-url': 'URL канала',
    'channel-info': 'Информация о канале',
    'channel-details': 'Детали канала',
    'no-channels': 'Нет каналов',
    'active-channel': 'Активный канал',
    'channel-management': 'Управление каналами',
    'connect-telegram-channel': 'Подключить Telegram-канал',
    'channel-list': 'Список каналов',
    'connected-channels': 'Подключенные каналы',
    'verification-status': 'Статус верификации',
    'verify-channel': 'Верифицировать канал',
    'connect-new-channel': 'Подключить новый канал',
    'manage-channels': 'Управление каналами',
    'channel-settings': 'Настройки канала',
    subscribers: 'Подписчики',
    'owner-ru': 'Владелец',
    'country': 'Страна',
    'russia': 'Россия',
    'created-at': 'Создан',
    'last-activity': 'Последняя активность',
    'channel-type': 'Тип канала',
    'public-channel': 'Публичный канал',
    'private-channel': 'Приватный канал',
    'total': 'Всего',
    
    // Analytics
    'analytics-overview': 'Обзор аналитики',
    'performance-metrics': 'Показатели эффективности',
    'audience-analysis': 'Анализ аудитории',
    'content-performance': 'Эффективность контента',
    'growth-trends': 'Тренды роста',
    'engagement-analysis': 'Анализ вовлеченности',
    'top-posts': 'Топ постов',
    'subscriber-growth': 'Рост подписчиков',
    'reach-analysis': 'Анализ охвата',
    'time-period': 'Период времени',
    'last-7-days': 'Последние 7 дней',
    'last-30-days': 'Последние 30 дней',
    'last-90-days': 'Последние 90 дней',
    'custom-range': 'Произвольный период',
    'select-channel-to-view-analytics': 'Выберите канал для просмотра аналитики',
    'views': 'Просмотры',
    'likes': 'Лайки',
    'shares': 'Репосты',
    'comments': 'Комментарии',
    'click-through-rate': 'CTR',
    'reach': 'Охват',
    'impressions': 'Показы',
    'growth-rate': 'Темп роста',
    'top-performing-posts': 'Лучшие посты',
    'audience-insights': 'Анализ аудитории',
    'channel-analytics': 'Аналитика канала',
    'detailed-analytics': 'Подробная аналитика и статистика',
    'analytics-for-channel': 'Аналитика для канала',
    'this-month': 'за этот месяц',
    'total-reactions': 'Всего реакций',
    'total-forwards': 'Всего репостов',
    'reactions': 'Реакции',
    'forwards': 'Репосты',
    
    // Scheduler module - comprehensive translations
    'scheduler-description': 'Планирование и управление постами',
    'schedule-post': 'Запланировать пост',
    'post': 'Пост',
    'list': 'Список',
    'calendar': 'Календарь',
    'week': 'Неделя',
    'month': 'Месяц',
    'prev': 'Назад',
    'next': 'Вперед',
    'today': 'Сегодня',
    'posts-for': 'Посты на',
    'no-posts-scheduled-for-date': 'Нет запланированных постов на эту дату',
    'no-scheduled-posts': 'Нет запланированных постов',
    'create-first-post': 'Создать первый пост',
    'select-channel-to-continue': 'Выберите канал для продолжения',
    'publishing': 'Публикуется...',
    'published': 'Опубликовано',
    'publish': 'Опубликовать',
    'post-published': 'Пост опубликован',
    'error-publishing-post': 'Ошибка публикации поста',
    'post-updated-successfully': 'Пост успешно обновлен',
    'error-updating-post': 'Ошибка обновления поста',
    'post-scheduled-successfully': 'Пост успешно запланирован',
    'error-scheduling-post': 'Ошибка планирования поста',
    'select-channel-first': 'Сначала выберите канал',
    'confirm-delete-post': 'Вы уверены, что хотите удалить этот пост?',
    'post-deleted': 'Пост удален',
    'error-deleting-post': 'Ошибка удаления поста',
    'scheduled-posts': 'Запланированные посты',
    'calendar-view': 'Просмотр календаря',
    'list-view': 'Просмотр списка',
    'weekly-view': 'Еженедельный просмотр',
    'monthly-view': 'Ежемесячный просмотр',
    'schedule-date': 'Дата планирования',
    'schedule-time': 'Время планирования',
    'post-content': 'Содержимое поста',
    'media-files': 'Медиафайлы',
    'poll-options': 'Варианты опроса',
    'post-type': 'Тип поста',
    'text-post': 'Текстовый пост',
    'photo-post': 'Пост с фото',
    'video-post': 'Пост с видео',
    'audio-post': 'Аудио пост',
    'document-post': 'Пост с документом',
    'poll-post': 'Опрос',
    'schedule-new-post': 'Запланировать новый пост',
    'edit-scheduled-post': 'Редактировать запланированный пост',
    'post-status': 'Статус поста',
    'pending': 'Ожидает',
    'sent': 'Отправлено',
    'failed': 'Ошибка',
    'draft': 'Черновик',
    'posts-scheduled': 'постов запланировано',
    
    // Assistant module translations
    'assistant-description': 'ИИ-помощник для автоматизации управления каналами',
    'ai-features': 'Возможности ИИ',
    'content-generation': 'Генерация контента',
    'content-generation-desc': 'Создание уникального контента для ваших каналов',
    'generate-post': 'Сгенерировать пост',
    'image-generation': 'Генерация изображений',
    'image-generation-desc': 'Создание изображений для постов с помощью ИИ',
    'create-image': 'Создать изображение',
    'analytics-insights': 'Аналитические инсайты',
    'analytics-insights-desc': 'Анализ данных и получение рекомендаций',
    'analyze-data': 'Анализировать данные',
    'schedule-optimization': 'Оптимизация расписания',
    'schedule-optimization-desc': 'Оптимальное время для публикации постов',
    'optimize-schedule': 'Оптимизировать расписание',
    'ai-chat': 'ИИ-чат',
    'ai-chat-description': 'Общайтесь с ИИ-ассистентом для получения помощи',
    'start-conversation': 'Начните разговор с ИИ-ассистентом',
    'type-message': 'Введите сообщение...',
    'quick-actions': 'Быстрые действия',
    'quick-actions-description': 'Популярные запросы к ИИ-ассистенту',
    'generate-post-idea': 'Сгенерировать идею поста',
    'improve-engagement': 'Улучшить вовлеченность',
    'analyze-competitors': 'Анализ конкурентов',
    'optimize-hashtags': 'Оптимизировать хештеги',
    'create-content-plan': 'Создать контент-план',
    'ai-response-placeholder': 'Это демонстрационный ответ ИИ-ассистента. В будущем здесь будет интеграция с реальным ИИ.',
    
    // Profile module translations
    'personal-information': 'Личная информация',
    'verified': 'Верифицирован',
    'location': 'Местоположение',
    'about': 'О себе',
    'full-name': 'Полное имя',
    'position': 'Должность',
    'bio': 'О себе',
    'about-placeholder': 'Расскажите о себе...',
    'statistics': 'Статистика',
    'active-channels': 'Активных каналов',
    'published-posts': 'Опубликованных постов',
    'account-settings': 'Настройки аккаунта',
    'security': 'Безопасность',
    'activity-history': 'История активности',
    'telegram-profile': 'Telegram профиль',
    'channel-administrator': 'Администратор канала',
    'moscow-russia': 'Москва, Россия',
    
    // Settings module translations
    'language-and-region': 'Язык и регион',
    'language-region-desc': 'Настройки языка интерфейса и региональных параметров',
    'telegram-integration': 'Telegram интеграция',
    'telegram-integration-desc': 'Настройки подключения к Telegram API и ботам',
    'database': 'База данных',
    'database-desc': 'Настройки подключения к Supabase и управление данными',
    'notifications-settings': 'Уведомления',
    'notifications-desc': 'Настройки push-уведомлений и email оповещений',
    'security-desc': 'Настройки безопасности аккаунта и доступа',
    'appearance-desc': 'Настройки темы, цветов и отображения интерфейса',
    'team': 'Команда',
    'team-desc': 'Управление участниками команды и правами доступа',
    'timezone': 'Временная зона',
    'date-format': 'Формат даты',
    'time-format': 'Формат времени',
    'russian-format': 'Российский',
    'american-format': 'Американский',
    'iso-format': 'ISO',
    'european-format': 'Европейский',
    '24h-format': '24-часовой формат',
    '12h-format': '12-часовой формат (AM/PM)',
    'data-management': 'Управление данными',
    'export-data': 'Экспорт данных',
    'import-data': 'Импорт данных',
    'push-notifications': 'Push-уведомления',
    'new-messages': 'Новые сообщения',
    'new-messages-desc': 'Уведомления о новых сообщениях в каналах',
    'scheduled-posts-notifications': 'Запланированные посты',
    'scheduled-posts-desc': 'Напоминания о публикации постов',
    'channel-statistics': 'Статистика каналов',
    'channel-statistics-desc': 'Еженедельные отчеты по каналам',
    'publishing-errors': 'Ошибки публикации',
    'publishing-errors-desc': 'Уведомления об ошибках при публикации',
    'email-notifications': 'Email уведомления',
    'weekly-reports': 'Еженедельные отчеты',
    'weekly-reports-desc': 'Статистика по каналам и постам',
    'critical-errors': 'Критические ошибки',
    'critical-errors-desc': 'Уведомления о системных ошибках',
    'product-news': 'Новости продукта',
    'product-news-desc': 'Обновления и новые функции',
    'sounds-vibration': 'Звуки и вибрация',
    'notification-sound': 'Звук уведомлений',
    'vibration': 'Вибрация',
    'account-security': 'Безопасность аккаунта',
    'two-factor-auth': 'Двухфакторная аутентификация',
    'two-factor-desc': 'Дополнительная защита аккаунта',
    'setup': 'Настроить',
    'auto-logout': 'Автоматический выход',
    'auto-logout-desc': 'Выход после периода бездействия',
    'api-tokens': 'API и токены',
    'api-keys': 'API ключи',
    'api-keys-desc': 'Управление API ключами для интеграций',
    'manage-keys': 'Управлять ключами',
    'active-sessions': 'Активные сессии',
    'active-sessions-desc': 'Просмотр и управление активными сессиями',
    'show-sessions': 'Показать сессии',
    'backup': 'Резервное копирование',
    'auto-backup': 'Автоматическое резервирование',
    'auto-backup-desc': 'Ежедневное создание резервных копий',
    'create-backup': 'Создать резервную копию',
    'interface-theme': 'Тема интерфейса',
    'choose-theme': 'Выберите тему',
    'auto-switch': 'Автоматическое переключение',
    'auto-switch-desc': 'Переключение темы по времени суток',
    'display': 'Отображение',
    'font-size': 'Размер шрифта',
    'small': 'Маленький',
    'medium': 'Средний',
    'large': 'Большой',
    'compact-mode': 'Компактный режим',
    'compact-mode-desc': 'Уменьшенные отступы и элементы',
    'animations': 'Анимации',
    'animations-desc': 'Плавные переходы между страницами',
    'color-scheme': 'Цветовая схема',
    'team-members': 'Участники команды',
    'administrator': 'Администратор',
    'owner': 'Владелец',
    'moderator': 'Модератор',
    'invite-member': 'Пригласить участника',
    'roles-permissions': 'Роли и права доступа',
    'default-role': 'Роль по умолчанию',
    'viewer': 'Просмотр',
    'editor': 'Редактор',
    'admin': 'Администратор',
    'require-invitation-confirmation': 'Требовать подтверждение приглашений',
    'invitation-confirmation-desc': 'Новые участники должны подтвердить приглашение',
    'module-settings': 'Настройки для этого модуля уже реализованы',
    'appearance': 'Внешний вид',
  },
  en: {
    // Navigation
    dashboard: 'Dashboard',
    channels: 'Channels',
    analytics: 'Analytics',
    scheduler: 'Scheduler',
    assistant: 'Assistant',
    partners: 'Partners',
    marketplace: 'Marketplace',
    notifications: 'Notifications',
    profile: 'Profile',
    settings: 'Settings',
    
    // Common
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    close: 'Close',
    refresh: 'Refresh',
    search: 'Search',
    filter: 'Filter',
    sort: 'Sort',
    export: 'Export',
    import: 'Import',
    
    // Auth
    login: 'Login',
    logout: 'Logout',
    register: 'Register',
    email: 'Email',
    password: 'Password',
    'confirm-password': 'Confirm Password',
    'forgot-password': 'Forgot Password?',
    'remember-me': 'Remember Me',
    
    // Dashboard
    'total-channels': 'Total Channels',
    'total-posts': 'Total Posts',
    'total-views': 'Total Views',
    'total-subscribers': 'Total Subscribers',
    'total-reach': 'Total Reach',
    'average-engagement': 'Average Engagement',
    'overview': 'Overview of all channels',
    'overview-for-channel': 'Channel overview',
    'recent-posts': 'Recent Posts',
    'no-recent-posts': 'No recent posts',
    'no-scheduled-posts-for-channel': 'No scheduled posts for this channel',
    'no-channel-selected': 'No channel selected',
    'select-channel-to-view-dashboard': 'Select a channel to view analytics',
    'view-all-posts': 'View All Posts',
    'view-all-requests': 'View All Requests',
    'posts-this-month': 'Posts This Month',
    'engagement-rate': 'Engagement Rate',
    'revenue': 'Revenue',
    'switching-channel': 'Switching channel...',
    'partner-revenue': 'Partner Revenue',
    'total-partner-revenue': 'Total Partner Revenue',
    'monthly-partner-income': 'Monthly Income',
    'rub': '$',
    'revenue-summary': 'Revenue Summary',
    'partner-revenue-overview': 'Partner program revenue overview',
    'total-revenue': 'Total Revenue',
    'revenue-by-partner': 'Revenue by Partner',
    'no-partners': 'No Partners',
    'view-all-partners': 'All Partners',
    'latest-posts-across-channels': 'Latest posts across all channels',
    'no-data': 'No data',
    
    // Channel Management
    'add-channel': 'Add Channel',
    'channel-name': 'Channel Name',
    'channel-username': 'Channel Username',
    'channel-description': 'Channel Description',
    'channel-url': 'Channel URL',
    'channel-info': 'Channel Info',
    'channel-details': 'Channel Details',
    'no-channels': 'No Channels',
    'active-channel': 'Active Channel',
    'channel-management': 'Channel Management',
    'connect-telegram-channel': 'Connect Telegram Channel',
    'channel-list': 'Channel List',
    'connected-channels': 'Connected Channels',
    'verification-status': 'Verification Status',
    'verify-channel': 'Verify Channel',
    'connect-new-channel': 'Connect New Channel',
    'manage-channels': 'Manage Channels',
    'channel-settings': 'Channel Settings',
    subscribers: 'Subscribers',
    'owner-ru': 'Owner',
    'country': 'Country',
    'russia': 'Russia',
    'created-at': 'Created',
    'last-activity': 'Last Activity',
    'channel-type': 'Channel Type',
    'public-channel': 'Public Channel',
    'private-channel': 'Private Channel',
    'total': 'Total',
    
    // Analytics
    'analytics-overview': 'Analytics Overview',
    'performance-metrics': 'Performance Metrics',
    'audience-analysis': 'Audience Analysis',
    'content-performance': 'Content Performance',
    'growth-trends': 'Growth Trends',
    'engagement-analysis': 'Engagement Analysis',
    'top-posts': 'Top Posts',
    'subscriber-growth': 'Subscriber Growth',
    'reach-analysis': 'Reach Analysis',
    'time-period': 'Time Period',
    'last-7-days': 'Last 7 Days',
    'last-30-days': 'Last 30 Days',
    'last-90-days': 'Last 90 Days',
    'custom-range': 'Custom Range',
    'select-channel-to-view-analytics': 'Select a channel to view analytics',
    'views': 'Views',
    'likes': 'Likes',
    'shares': 'Shares',
    'comments': 'Comments',
    'click-through-rate': 'CTR',
    'reach': 'Reach',
    'impressions': 'Impressions',
    'growth-rate': 'Growth Rate',
    'top-performing-posts': 'Top Performing Posts',
    'audience-insights': 'Audience Insights',
    'channel-analytics': 'Channel Analytics',
    'detailed-analytics': 'Detailed analytics and statistics',
    'analytics-for-channel': 'Analytics for channel',
    'this-month': 'this month',
    'total-reactions': 'Total Reactions',
    'total-forwards': 'Total Forwards',
    'reactions': 'Reactions',
    'forwards': 'Forwards',
    
    // Scheduler module - comprehensive translations
    'scheduler-description': 'Schedule and manage posts',
    'schedule-post': 'Schedule Post',
    'post': 'Post',
    'list': 'List',
    'calendar': 'Calendar',
    'week': 'Week',
    'month': 'Month',
    'prev': 'Previous',
    'next': 'Next',
    'today': 'Today',
    'posts-for': 'Posts for',
    'no-posts-scheduled-for-date': 'No posts scheduled for this date',
    'no-scheduled-posts': 'No scheduled posts',
    'create-first-post': 'Create First Post',
    'select-channel-to-continue': 'Select a channel to continue',
    'publishing': 'Publishing...',
    'published': 'Published',
    'publish': 'Publish',
    'post-published': 'Post published',
    'error-publishing-post': 'Error publishing post',
    'post-updated-successfully': 'Post updated successfully',
    'error-updating-post': 'Error updating post',
    'post-scheduled-successfully': 'Post scheduled successfully',
    'error-scheduling-post': 'Error scheduling post',
    'select-channel-first': 'Select a channel first',
    'confirm-delete-post': 'Are you sure you want to delete this post?',
    'post-deleted': 'Post deleted',
    'error-deleting-post': 'Error deleting post',
    'scheduled-posts': 'Scheduled Posts',
    'calendar-view': 'Calendar View',
    'list-view': 'List View',
    'weekly-view': 'Weekly View',
    'monthly-view': 'Monthly View',
    'schedule-date': 'Schedule Date',
    'schedule-time': 'Schedule Time',
    'post-content': 'Post Content',
    'media-files': 'Media Files',
    'poll-options': 'Poll Options',
    'post-type': 'Post Type',
    'text-post': 'Text Post',
    'photo-post': 'Photo Post',
    'video-post': 'Video Post',
    'audio-post': 'Audio Post',
    'document-post': 'Document Post',
    'poll-post': 'Poll',
    'schedule-new-post': 'Schedule New Post',
    'edit-scheduled-post': 'Edit Scheduled Post',
    'post-status': 'Post Status',
    'pending': 'Pending',
    'sent': 'Sent',
    'failed': 'Failed',
    'draft': 'Draft',
    'posts-scheduled': 'posts scheduled',
    
    // Assistant module translations
    'assistant-description': 'AI assistant for channel management automation',
    'ai-features': 'AI Features',
    'content-generation': 'Content Generation',
    'content-generation-desc': 'Create unique content for your channels',
    'generate-post': 'Generate Post',
    'image-generation': 'Image Generation',
    'image-generation-desc': 'Create images for posts using AI',
    'create-image': 'Create Image',
    'analytics-insights': 'Analytics Insights',
    'analytics-insights-desc': 'Analyze data and get recommendations',
    'analyze-data': 'Analyze Data',
    'schedule-optimization': 'Schedule Optimization',
    'schedule-optimization-desc': 'Optimal timing for post publishing',
    'optimize-schedule': 'Optimize Schedule',
    'ai-chat': 'AI Chat',
    'ai-chat-description': 'Chat with AI assistant for help',
    'start-conversation': 'Start conversation with AI assistant',
    'type-message': 'Type message...',
    'quick-actions': 'Quick Actions',
    'quick-actions-description': 'Popular AI assistant requests',
    'generate-post-idea': 'Generate Post Idea',
    'improve-engagement': 'Improve Engagement',
    'analyze-competitors': 'Analyze Competitors',
    'optimize-hashtags': 'Optimize Hashtags',
    'create-content-plan': 'Create Content Plan',
    'ai-response-placeholder': 'This is a demo AI assistant response. Real AI integration will be here in the future.',
    
    // Profile module translations
    'personal-information': 'Personal Information',
    'verified': 'Verified',
    'location': 'Location',
    'about': 'About',
    'full-name': 'Full Name',
    'position': 'Position',
    'bio': 'Bio',
    'about-placeholder': 'Tell us about yourself...',
    'statistics': 'Statistics',
    'active-channels': 'Active Channels',
    'published-posts': 'Published Posts',
    'account-settings': 'Account Settings',
    'security': 'Security',
    'activity-history': 'Activity History',
    'telegram-profile': 'Telegram Profile',
    'channel-administrator': 'Channel Administrator',
    'moscow-russia': 'Moscow, Russia',
    
    // Settings module translations
    'language-and-region': 'Language and Region',
    'language-region-desc': 'Interface language and regional settings',
    'telegram-integration': 'Telegram Integration',
    'telegram-integration-desc': 'Telegram API and bot connection settings',
    'database': 'Database',
    'database-desc': 'Supabase connection settings and data management',
    'notifications-settings': 'Notifications',
    'notifications-desc': 'Push notifications and email alerts settings',
    'security-desc': 'Account security and access settings',
    'appearance-desc': 'Theme, colors and interface display settings',
    'team': 'Team',
    'team-desc': 'Team member management and access rights',
    'timezone': 'Timezone',
    'date-format': 'Date Format',
    'time-format': 'Time Format',
    'russian-format': 'Russian',
    'american-format': 'American',
    'iso-format': 'ISO',
    'european-format': 'European',
    '24h-format': '24-hour format',
    '12h-format': '12-hour format (AM/PM)',
    'data-management': 'Data Management',
    'export-data': 'Export Data',
    'import-data': 'Import Data',
    'push-notifications': 'Push Notifications',
    'new-messages': 'New Messages',
    'new-messages-desc': 'Notifications about new messages in channels',
    'scheduled-posts-notifications': 'Scheduled Posts',
    'scheduled-posts-desc': 'Reminders about post publishing',
    'channel-statistics': 'Channel Statistics',
    'channel-statistics-desc': 'Weekly channel reports',
    'publishing-errors': 'Publishing Errors',
    'publishing-errors-desc': 'Notifications about publishing errors',
    'email-notifications': 'Email Notifications',
    'weekly-reports': 'Weekly Reports',
    'weekly-reports-desc': 'Channel and post statistics',
    'critical-errors': 'Critical Errors',
    'critical-errors-desc': 'System error notifications',
    'product-news': 'Product News',
    'product-news-desc': 'Updates and new features',
    'sounds-vibration': 'Sounds and Vibration',
    'notification-sound': 'Notification Sound',
    'vibration': 'Vibration',
    'account-security': 'Account Security',
    'two-factor-auth': 'Two-Factor Authentication',
    'two-factor-desc': 'Additional account protection',
    'setup': 'Setup',
    'auto-logout': 'Auto Logout',
    'auto-logout-desc': 'Logout after period of inactivity',
    'api-tokens': 'API and Tokens',
    'api-keys': 'API Keys',
    'api-keys-desc': 'Manage API keys for integrations',
    'manage-keys': 'Manage Keys',
    'active-sessions': 'Active Sessions',
    'active-sessions-desc': 'View and manage active sessions',
    'show-sessions': 'Show Sessions',
    'backup': 'Backup',
    'auto-backup': 'Auto Backup',
    'auto-backup-desc': 'Daily backup creation',
    'create-backup': 'Create Backup',
    'interface-theme': 'Interface Theme',
    'choose-theme': 'Choose Theme',
    'auto-switch': 'Auto Switch',
    'auto-switch-desc': 'Switch theme by time of day',
    'display': 'Display',
    'font-size': 'Font Size',
    'small': 'Small',
    'medium': 'Medium',
    'large': 'Large',
    'compact-mode': 'Compact Mode',
    'compact-mode-desc': 'Reduced spacing and elements',
    'animations': 'Animations',
    'animations-desc': 'Smooth transitions between pages',
    'color-scheme': 'Color Scheme',
    'team-members': 'Team Members',
    'administrator': 'Administrator',
    'owner': 'Owner',
    'moderator': 'Moderator',
    'invite-member': 'Invite Member',
    'roles-permissions': 'Roles and Permissions',
    'default-role': 'Default Role',
    'viewer': 'Viewer',
    'editor': 'Editor',
    'admin': 'Admin',
    'require-invitation-confirmation': 'Require Invitation Confirmation',
    'invitation-confirmation-desc': 'New members must confirm invitation',
    'module-settings': 'Settings for this module are already implemented',
    'appearance': 'Appearance',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'ru';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  const value = {
    language,
    setLanguage,
    t
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};
