// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://upirwcmwofvmjsqdqorj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwaXJ3Y213b2Z2bWpzcWRxb3JqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4OTAxMTYsImV4cCI6MjA2NDQ2NjExNn0.TLDJdYHZKVA8Zjv8-UITJNGimIdZ4oCVHz4bNdMWw9U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);